### ISSUE TITLE
Make PyPI package

### ISSUE THREAD

**Issue by OlaRonning** [EleutherAI/mp_nerf#3]
Hi,

Read your paper and want to incorporate mp nerf in my project. 

While cloning is doable, it would be significantly easier to use `pip install mp-nerf`. To process to upload the project to PyPI is described [here](https://packaging.python.org/tutorials/packaging-projects/). I'll gladly assist in doing so.

**Comment by hypnopump** [comment]
it is already provided as a PyPI package, doesn't it work as expected?

**Comment by OlaRonning** [comment]
Great! I just checked my command history, and I used `pip install mp_nerf` with `_` instead of `-`.  `pip install mp-nerf` does indeed work. Thanks for the quick reply. I'll close the issue.
